version: 2
project_name: go-jsonc

builds:
  - skip: true

changelog:
  skip: false
  use: git
  sort: asc
  groups:
    - title: BREAKING CHANGES
      regexp: '^(.*)!:'
      order: 0
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Bug fixes'
      regexp: '^.*?(bug|fix)(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999
  filters:
    exclude:
      - '^docs(\(.*\))?:'
      - '^ci(\(.*\))?:'
      - '^Merge'
      - typo
